[project]
name = "improvement-lab"
version = "0.1.0"
description = "Personal Code Lab"
authors = [
    { name = "Felipe Martin Rodriguez", email = "felipemrz01@gmail.com" }
]

[tool.ruff]
src=["app", "tests"]
line-length = 100
target-version = "py312"
exclude = [
  ".git",
  ".venv",
  "__pycache__",
  ".mypy_cache",
  ".pytest_cache",
  "dist",
  "build",
]

[tool.ruff.lint]
extend-select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle
    "F",  # Pyflakes
    "I",  # isort
    "UP",  # pyupgrade
    "D",  # pydocstyle
]
ignore = ["D104"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"